docs:
  image: alpine:latest
  script:
    - apk add yelp-tools yelp-xsl ninja-build meson itstool gettext bash openssh
    - mkdir ~/.ssh
    - echo -n $SSH_HOST_KEY | base64 -d >~/.ssh/known_hosts
    - eval `ssh-agent`
    - echo -n $SSH_PRIVATE_KEY | base64 -d | ssh-add -
    - bash build-aux/render-help.sh
    - scp -v -r doc-build/html scponly-shotwell-deploy@webstreams.de:doc
  artifacts:
    paths:
      - docs.tar
  rules:
    - if: $CI_COMMIT_BRANCH == "wip/ci"
