# Site settings
title: Shotwell
baseurl: "" # the subpath of your site, e.g. /blog/
                                 # usually empty. necessary for building absolute URIs
                                 # for metadata header
url: "https://shotwell-project.org"   # the base hostname & protocol for your site
sourceurl: "https://gitlab.gnome.org/GNOME/shotwell/-/tree/website" # "edit this website" link in the footer
description: "Shotwell is a personal photo manager."
issuesurl: "https://gitlab.gnome.org/GNOME/shotwell/-/issues" # issue tracker for website
permalink: /:title/
primary-color: "#26a269" #used in ios theme. further color customization in style.css  

# Build settings
markdown: kramdown
