#!/usr/bin/env bash
#
# Copyright 2011-2014 Yorba Foundation
#
# This software is licensed under the GNU LGPL (version 2.1 or later).
# See the COPYING file in this distribution.

if [ $# -ne 2 ]
then
    echo "usage:" `basename $0` "<unit-dir> <basename-no-ext>"
    echo " e.g.:" `basename $0` "frotz Gnusto"
    echo "       produces src/frotz/Gnusto.vala"
    exit 1
fi

mkdir -p src/$1
cp src/unit/rc/template.vala src/$1/$2.vala

echo "File $2.vala must be manually added to src/$1/mk/$1.mk."

