.TH "shotwell" "1"

.SH "NAME"
shotwell \- Digital photo manager

.SH "SYNOPSIS"
\fBshotwell \fR[\fIOPTION\fR]... [\fIFILE\fR]

.SH "DESCRIPTION"
.P
Shotwell is a digital photo organizer designed for the GNOME desktop environment.  It allows you to 
import photos from disk or camera, organize them in various ways, view them in full-window or fullscreen mode, and export them to share with others.

.SH "OPTIONS"
.B \-h, \-\-help
Show help options
.RE

.B \-d, \-\-datadir=FOLDER
.RS
Path to Shotwell's private data. Using \-d stand-alone without --profile --create is considered deprecated and should not be used anymore.
.RE

.B \-\-no-runtime-monitoring
.RS
Do not monitor library folder at runtime for changes
.RE

.B \-f, \-\-fullscreen
.RS
Open the viewer mode in fullscreen. Has no effect in library mode.
.RE

.B \-\-no-startup-progress
.RS
Don't display startup progress meter
.RE

.B \-V, \-\-version
.RS
Show the application's version
.RE

.B \-\-display=DISPLAY
.RS
X display to use
.RE

.B \-p, \-\-show-metadata
.RS
Dump all Exif, IPTC and XMP metadata of \f1FILE\fR
.RE

.B \-i, \-\-profile=PROFILE
.RS
Start shotwell with a different profile. A profile consists of a set of settings and a new private data dir. The data dir can be overriden by secifying \-\-datadir as well.
.RE

.B \-l, \-\-list-profiles
.RS
Show the available profiles
.RE

.B \-b, \-\-profile-browser
.RS
Show the available profiles in a dialog, with managing capabilities and the ability to start Shotwell with a specific profile by double-clicking.
.RE
.SH "EXAMPLES"
\fBshotwell
.RS
\fROpens Shotwell with the user's library.
.RE

\fBshotwell \fIFILE
.RS
\fROpens an image file for direct editing.  File is not imported into library and unsaved changes are lost on close.
.RE

\fBshotwell \-\-profile="Development environment"
.RS
\fROpens shotwell using the profile named "Development environment".
.RE

.SH "NOTES"
.P
Shotwell homepage: https://wiki.gnome.org/Apps/Shotwell
.P
Report bugs: https://gitlab.gnome.org/GNOME/shotwell/issues

.SH "AUTHOR"
.PP
This manual page was written by Jim Nelson jim@yorba.org and Allison Barlow allison@yorba.org.
