
PLUGIN := shotwell-publishing

PKGS := shotwell-publishing-1.0 \
        gtk+-2.0 \
        libsoup-2.4 \
        libxml-2.0 \
        webkit-1.0 \
        shotwell-spit-1.0

SRC_FILES := \
	shotwell-publishing.vala \
	FacebookPublishing.vala

include ../Makefile.plugin.mk

