
PLUGIN := shotwell-publishing

PKGS := \
	gtk+-2.0 \
	libsoup-2.4 \
	libxml-2.0 \
	webkit-1.0 \
	gexiv2 \
	gee-1.0

SRC_FILES := \
	shotwell-publishing.vala \
	FacebookPublishing.vala \
	PicasaPublishing.vala \
	FlickrPublishing.vala \
	YouTubePublishing.vala \
	RESTSupport.vala

include ../Makefile.plugin.mk

