
PLUGIN := shotwell-publishing-extras

PKGS := \
	gtk+-2.0 \
	libsoup-2.4 \
	libxml-2.0 \
	webkit-1.0 \
	json-glib-1.0 \
	gee-1.0

SRC_FILES := \
	shotwell-publishing-extras.vala \
	YandexPublishing.vala \
	../common/RESTSupport.vala

include ../Makefile.plugin.mk

