.TH "shotwell" "1"
.SH "NAME"
shotwell \- Digital photo organizer
.SH "SYNOPSIS"
\fBshotwell
.SH "DESCRIPTION"
.B shotwell
is a digital photo organizer designed for the GNOME desktop environment.  It allows you to import
photos from disk or camera, organize them in various ways, view them in full-window or fullscreen
mode, and export them to share with others.
.SH "AUTHOR"
.PP
This manual page was written by Jim Nelson jim@yorba.org.
