
PLUGIN := shotwell-transitions
PKGS := shotwell-transitions-1.0

SRC_FILES := \
	shotwell-transitions.vala \
	FadeEffect.vala \
	SlideEffect.vala \
	CrumbleEffect.vala

include ../Makefile.plugin.mk

