
PLUGIN := shotwell-transitions

SRC_FILES := \
	shotwell-transitions.vala \
	FadeEffect.vala \
	SlideEffect.vala \
	CrumbleEffect.vala \
	BlindsEffect.vala \
	CircleEffect.vala \
	CirclesEffect.vala \
	ClockEffect.vala

RC_FILES := \
	slideshow-plugin.png

include ../Makefile.plugin.mk

